name: 'IBM Cloud CLI'
description: 'Install and configure IBM Cloud CLI to talk to IBM Cloud'
inputs:
  APIKEY:
    description: 'Your API key to access IBM Cloud'
    required: true
  CLOUD_REGION:
    description: 'The region to access IBM Cloud'
    required: false
    default: 'us-south'
  RESOURCE_GROUP:
    description: 'The resource group to access IBM Cloud'
    required: false
    default: 'Default'
  IMAGE_TAG:
    description: 'The image tag to build'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.APIKEY }}
    - ${{ inputs.CLOUD_REGION }}
    - ${{ inputs.RESOURCE_GROUP }}
    - ${{ inputs.IMAGE_TAG }}

branding:
  icon: 'upload-cloud'  
  color: 'blue'
